nelmio_api_doc:
    areas:
        path_patterns: # an array of regexps (document only routes under /api, except /api/doc)
            - ^/api(?!/doc$)
        #host_patterns: # document only routes with a host of the form api.*
        #    - ^api\.
    documentation:
        info:
            title: My App
            description: Esta es una aplicación increíble!
            version: 1.0.0
            x-build: #CommitHash
        #servers:
        #    - url: http://api.example.com/unsafe
        #        description: API over HTTP
        #    - url: https://api.example.com/secured
        #        description: API over HTTPS
        #components:
        #    securitySchemes:
        #        Bearer:
        #            type: http
        #            scheme: bearer
        #            bearerFormat: JWT
        #security:
        #    - Bearer: []